language: erlang
notifications:
  recipients:
    - arnaud.wetzel@kbrwadventure.com
otp_release:
  - 18.2.1
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.3.3.zip
  - unzip -d elixir v1.3.3.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
